from Calculus.ConstruccionCalculus.Constructora.EspecificacionesMateriales import ladrillo,bloque
from Calculus.ConstruccionCalculus.Constructora import GeneraListaMateriales as lista_materiales

lista_materiales.material_ParedTabiquesCerramiento_metros(bloque,1,1)